In [14]:
import torch
import numpy as np
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
g_checkpoint = torch.load('autovc.ckpt', map_location=device)

In [22]:
g_checkpoint.keys()

dict_keys(['model', 'optimizer'])

In [23]:
g_checkpoint['model'].keys()

odict_keys(['encoder.convolutions.0.0.conv.weight', 'encoder.convolutions.0.0.conv.bias', 'encoder.convolutions.0.1.weight', 'encoder.convolutions.0.1.bias', 'encoder.convolutions.0.1.running_mean', 'encoder.convolutions.0.1.running_var', 'encoder.convolutions.0.1.num_batches_tracked', 'encoder.convolutions.1.0.conv.weight', 'encoder.convolutions.1.0.conv.bias', 'encoder.convolutions.1.1.weight', 'encoder.convolutions.1.1.bias', 'encoder.convolutions.1.1.running_mean', 'encoder.convolutions.1.1.running_var', 'encoder.convolutions.1.1.num_batches_tracked', 'encoder.convolutions.2.0.conv.weight', 'encoder.convolutions.2.0.conv.bias', 'encoder.convolutions.2.1.weight', 'encoder.convolutions.2.1.bias', 'encoder.convolutions.2.1.running_mean', 'encoder.convolutions.2.1.running_var', 'encoder.convolutions.2.1.num_batches_tracked', 'encoder.lstm.weight_ih_l0', 'encoder.lstm.weight_hh_l0', 'encoder.lstm.bias_ih_l0', 'encoder.lstm.bias_hh_l0', 'encoder.lstm.weight_ih_l0_reverse', 'encoder.lstm.

We want to reset the weights in the following layers:

##### first conv and batchnorm layers in encoder.convolutions
'encoder.convolutions.0.0.conv.weight', 'encoder.convolutions.0.0.conv.bias', 'encoder.convolutions.0.1.weight', 'encoder.convolutions.0.1.bias', 'encoder.convolutions.0.1.running_mean', 'encoder.convolutions.0.1.running_var', 'encoder.convolutions.0.1.num_batches_tracked'

##### decoder.linear_projection
'decoder.linear_projection.linear_layer.weight', 'decoder.linear_projection.linear_layer.bias'

##### first and last conv and batchnorm layers in Postnet.convolutions
'postnet.convolutions.0.0.conv.weight', 'postnet.convolutions.0.0.conv.bias', 'postnet.convolutions.0.1.weight', 'postnet.convolutions.0.1.bias', 'postnet.convolutions.0.1.running_mean', 'postnet.convolutions.0.1.running_var', 'postnet.convolutions.0.1.num_batches_tracked'


'postnet.convolutions.4.1.weight', 'postnet.convolutions.4.1.bias', 'postnet.convolutions.4.1.running_mean', 'postnet.convolutions.4.1.running_var', 'postnet.convolutions.4.1.num_batches_tracked'



In [21]:
g_checkpoint['model']

OrderedDict([('encoder.convolutions.0.0.conv.weight',
              tensor([[[ 0.1833,  0.0602, -0.0952, -0.1923, -0.1413],
                       [ 0.2417,  0.0955, -0.1547, -0.2782, -0.1997],
                       [ 0.1635, -0.0322, -0.2667, -0.3990, -0.2944],
                       ...,
                       [-0.0382, -0.0140, -0.0484,  0.0116, -0.0458],
                       [-0.0160,  0.0317, -0.0360, -0.0566, -0.0289],
                       [ 0.0685,  0.1405,  0.0845,  0.0319,  0.0369]],
              
                      [[ 0.0040, -0.0113,  0.0536,  0.1625,  0.2285],
                       [ 0.0445,  0.0437, -0.0046,  0.1191,  0.2217],
                       [ 0.2145,  0.1754,  0.0396,  0.1471,  0.3024],
                       ...,
                       [-0.0157, -0.0300,  0.0228, -0.0512, -0.1226],
                       [-0.0183, -0.0105, -0.0455,  0.2475,  0.2633],
                       [ 0.0533,  0.0891,  0.1174,  0.3093,  0.2596]],
              
                  

In [20]:
g_checkpoint['model']['encoder.convolutions.0.0.conv.weight'].shape

torch.Size([512, 336, 5])

In [1]:
import numpy as np

In [6]:
np.save('/work3/dgro/VCTK-Corpus-0/nina_test.npy','spmel/p001_003.npy')

In [1]:
import uuid

In [6]:
import os
if os.listdir('/work3/dgro/VCTK-Corpus-0/'+'spmel'):
    print('empty')

empty


In [ ]:
config.data_dir+config.speaker_embed 

In [8]:
from model_vc import Generator
import torch 
dim_neck = 32
dim_emb = 256
dim_pre = 512
freq = 32
speaker_embed = True
lr = 0.001

G = Generator(dim_neck, dim_emb, dim_pre, freq, speaker_embed)        

g_optimizer = torch.optim.Adam(G.parameters(), lr)

#lr_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(g_optimizer, T_max=10, eta_min=0)

lr_scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(g_optimizer, 'min')

In [9]:
lr_scheduler.get_last_lr()[0] # cosine

AttributeError: 'ReduceLROnPlateau' object has no attribute 'get_last_lr'

In [22]:
lr_scheduler.optimizer.param_groups[0]['lr'] # plateau

0.001

In [17]:
import os
len(os.listdir('/work3/dgro/VCTK-Corpus-0/stft_val'))

14

In [25]:
import numpy as np
npy_file = np.load('/work3/dgro/VCTK-Corpus-0/stft/p256/p256_160_mic2.npy')

In [26]:
npy_file.shape

(169, 513)

In [38]:
import numpy as np
with open(os.path.join('/work3/dgro/VCTK-Corpus-0/stft/', 'train.pkl'), 'rb') as file:
    train = pickle.load(file)

    #create metadata for testing
    #Format is [subject, embedding, melspec] 
    metadata = []
    for subject in train:
        first_mel_spec = np.load('/work3/dgro/VCTK-Corpus-0/stft/'+subject[2])
        metadata.append(subject[0:2] + [first_mel_spec] + [subject[2]])
        
    with open(os.path.join('/work3/dgro/VCTK-Corpus-0', 'stft_metadata.pkl'), 'wb') as handle:
            pickle.dump(metadata, handle)

In [ ]:
import pickle
with open(os.path.join('/work3/dgro/VCTK-Corpus-0/', 'stft_metadata.pkl'), 'rb') as file:
        metadata = pickle.load(file)

In [ ]:
metadata[0][2].shape

In [6]:
import torch
import os
os.listdir('/work3/dgro/VCTK-Corpus-0/models/')
#checkpoint = torch.load("/work3/dgro/VCTK-Corpus-0/models/model_checkpoint_mel.pth")
#self.G.load_state_dict(checkpoint["state_dict"])

['model_checkpoint_mel.pth', 'model_checkpoint_STFT.pth']

In [32]:
import soundfile as sf
from scipy import signal
import librosa

def butter_highpass(fs, cutoff, order):
        nyq = 0.5 * fs
        normal_cutoff = cutoff / nyq
        b, a = signal.butter(order, normal_cutoff, btype='high', analog=False)
        return b, a

b, a = butter_highpass(fs=16000, cutoff=30, order=5)

path = '/work3/dgro/VCTK-Corpus-0/wav48_silence_trimmed/p227/p227_335_mic2.flac'
x_fs = librosa.load(path, sr=16000),
x = x_fs[0][0]
#Remove drifting noise
y = signal.filtfilt(b, a, x)
# Add a little random noise for model roubstness
#wav = y * 0.96 + (prng.rand(y.shape[0])-0.5)*1e-06

In [33]:
x.shape, y.shape

((32849,), (32849,))

In [35]:
x.min(), x.max()

(-0.23405065, 0.32176462)

In [34]:
y.min(), y.max()

(-0.23036241000580293, 0.32120244491907324)

In [7]:
fs

48000

In [10]:
import torch
checkpoint = torch.load('chkpnt_spmel_reproducedAutoVC_new_22April23_1444_43.ckpt', map_location=torch.device('cpu'))

In [13]:
import torch
def flatten_params(model):
    return torch.cat([param.data.view(-1) for param in model.parameters()], 0)

In [35]:
from model_vc_mel import Generator
G = Generator(32, 256, 512, 32)

checkpoint = torch.load('chkpnt_spmel_reproducedAutoVC_new_22April23_1444_43_resumed_resumed.ckpt',map_location=torch.device('cpu'))
G.load_state_dict(checkpoint['state_dict'])

<All keys matched successfully>

In [31]:
flatten_params(G)

tensor([ 0.0307,  0.0552,  0.0456,  ..., -0.0004, -0.0005, -0.0007])

In [36]:
checkpoint

{'epoch': 1049600,
 'state_dict': OrderedDict([('encoder.convolutions.0.0.conv.weight',
               tensor([[[ 0.0327,  0.0589,  0.0530, -0.0215,  0.0874],
                        [ 0.0868,  0.0181, -0.1098, -0.0546,  0.0972],
                        [ 0.0916,  0.1114, -0.0536,  0.0293,  0.1503],
                        ...,
                        [ 0.0070,  0.0344,  0.0936,  0.0471,  0.0532],
                        [ 0.0829,  0.0980,  0.0962,  0.0113,  0.0142],
                        [ 0.2076,  0.1485,  0.1843,  0.1094,  0.0979]],
               
                       [[ 0.0733,  0.0886,  0.2603,  0.3238,  0.3595],
                        [-0.0104, -0.0221,  0.1524,  0.1975,  0.2337],
                        [ 0.0680,  0.0642,  0.0513,  0.1137,  0.1067],
                        ...,
                        [-0.0221, -0.0939, -0.0541, -0.0796, -0.0966],
                        [-0.0916, -0.0749, -0.1094, -0.0388, -0.0413],
                        [ 0.0909,  0.0791,  0.1176,  0.0